app:
  build: ./
  expose:
    - "80"
  ports:
    - "3000:80"
  links:
    - database:mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=template.localhost

# Default Mongo Port: 27017
database:
  image: mongo
#  build: ./mongodb/
#  volumes:
# Save Database to HOST Filesystem
#    - ./mongodb/database:/data/db:rw
