app:
  build: ./
#  restart: always
  expose:
    - "80"
  ports:
    - "3000:80"
  links:
    - database:mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=template.experimental.build.slidewiki.org

# Default Mongo Port: 27017
database:
  build: ./mongodb/
#  restart: always
#  mem_limit: 1G
#  volumes:
# Save Database to HOST Filesystem
#    - ./mongodb/database:/data/db:rw
