service:
  image: slidewiki/deckservice
  restart: always
  expose:
    - "80"
  external_links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=deckservice.185.101.156.130.xip.io
