service:
  image: slidewiki/microservicetemplate
  restart: always
  expose:
    - "80"
  external_links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=template.30230.hostserv.eu
